<?php

use Illuminate\Database\Seeder;
use App\Entities\Pathology;

class PathologiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pathologies = [
            "Acalculia / Agrafia"=>"",
            "Aconselhamento não específico"=>"",
            "Afasia / Disfasia"=>"",
            "Afonia / Perda da Voz"=>"",
            "Agnosia"=>"",
            "Alimentação Vagarosa do RN"=>"",
            "Anquiloglossia"=>"",
            "Apraxia"=>"",
            "Assistência e exame da Nutriz (Supervisão do Aleitamento Materno)"=>"",
            "Ataxia Hereditária"=>"",
            "Ataxia Hereditária não especificada"=>"",
            "Atraso de Linguagem"=>"",
            "Ausência de Úvula"=>"",
            "Deficiência Auditiva"=>"",
            "Déficit de Atenção sem Hiperatividade"=>"",
            "Deglutição Atípica e Respiração Bucal"=>"",
            "Dificuldade Neonatal na Amamentação no Peito"=>"",
            "Disacusia"=>"",
            "Disartria - Retardo Específico na Motricidade"=>"",
            "Discalculia - Adulto"=>"",
            "Disfagia"=>"",
            "Disfasia e Afasia"=>"",
            "Disfemia"=>"",
            "Disfonia"=>"",
            "Disgrafia / Disortografia"=>"",
            "Dislalia ou transtornos específicos da articulação da fala (distúrbio articulatório)"=>"",
            "Dislexia de Desenvolvimento"=>"",
            "Dislexia e Alexia"=>"",
            "Dispraxia / Apraxia"=>"",
            "Distonia (Discinesia)"=>"",
            "Distúrbio Simples de Atividade e Atenção"=>"",
            "Doença de Alzheimer"=>"",
            "Doença de Huntington"=>"",
            "Doença de Parkinson"=>"",
            "Estenose Subglótica Congênita"=>"",
            "Estridor Congênito da Laringe"=>"",
            "Exames de Rotina de Saúde à Criança"=>"",
            "Exames dos ouvidos e da audição"=>"",
            "Fenda Bilateral do Pálato Mole com Fenda Labial"=>"",
            "Fenda Bilateral do Pálato com Fenda Labial, não especificada"=>"",
            "Fenda Bilateral do Pálato Duro"=>"",
            "Fenda Bilateral do Pálato Duro com Fenda Labial"=>"",
            "Fenda Bilateral do Pálato Mole"=>"",
            "Fenda Bilateral dos Pálatos Duro e Mole"=>"",
            "Fenda Bilateral dos Pálatos Duro Mole com Fenda Labial"=>"",
            "Fenda da Úvula"=>"",
            "Fenda Labial Bilateral"=>"",
            "Fenda Labial Bilateral"=>"",
            "Fenda Labial Unilateral"=>"",
            "Fenda Mediana do Pálato"=>"",
            "Fenda Palatina não especificada, Billateral"=>"",
            "Fenda Palatina não especificada, Billateral"=>"",
            "Fenda Unilateral do Pálato Mole com Fenda Labial"=>"",
            "Fenda Unilateral do Pálato com Fenda Labial, não especificada"=>"",
            "Fenda Unilateral do Pálato Duro"=>"",
            "Fenda Unilateral do Pálato Duro"=>"",
            "Fenda Unilateral do Pálato Duro Mole com Fenda Labial"=>"",
            "Fenda Unilateral dos Pálatos Duro e Mole"=>"",
            "Fenda Unilateral dos Pálatos Duro Mole com Fenda Labial"=>"",
            "Gagueira"=>"",
            "Halitose"=>"",
            "Hipernasalidade e Hiponasalidade"=>"",
            "Hipoplasia da Laringe"=>"",
            "Laringocele"=>"",
            "Macroglossia e língua presa"=>"",
            "Malformações Congênitas dos Lábios, não classificadas em outra parte"=>"",
            "Maus Resultados Escolares"=>"",
            "Miastenias Gravis"=>"",
            "Oligofrenia Leve"=>"",
            "Outras Anomalias Congênitas da Parte Superior do Tubo Digestivo"=>"",
            "Outras Anomalias Dento - Faciais"=>"",
            "Outras Disfunções Simbólicas e as não especificadas (acalculia, agrafia)"=>"",
            "Outras Formas de Coréia"=>"",
            "Outras Malformações da Laringe"=>"",
            "Outros Distúrbios da Fala e os não especificados"=>"",
            "Outros Distúrbios da voz e os não especificados (mudanças de voz)"=>"",
            "Outros probl. relacionados com a educ. e c/ a alfabeta. (Ensino inadequado)"=>"",
            "Outros Transtornos do desenvolvimento da fala ou da Linguagem (RAL)"=>"",
            "Paciente Eutrófico (normal para a área pesquisada)"=>"",
            "Problema não específicos de aleitamento do RN"=>"",
            "Problemas de Aleitamento do RN"=>"",
            "Problemas não especificados relacionados com a educação e alfabetização"=>"",
            "Psicomotricidade"=>"",
            "Reabilitação da Linguagem"=>"",
            "Respiração Atípica"=>"",
            "Seguimento Pós-parto de rotina"=>"",
            "Sindrome de Down"=>"",
            "Surdez"=>"",
            "Surdez de Condução"=>"",
            "Surdez não especificada"=>"",
            "Transtorno da Articulação Temporo-mandibular"=>"",
            "Transtorno de desenvolvimento de expressão Escrita"=>"",
            "Transtorno de Desenvolvimento Misto das Habilidades Escolares"=>"",
            "Transtorno Hipercinético da Conduta"=>"",
            "Transtorno Misto das Habilidades Escolares"=>"",
            "Tremor Essencial"=>"",
            "Anomalias Dento - Faciais" => "Inclusive Mal - Oclusão",
            "outros" => "Cuidados envolvendo o uso de procedimentos de reabilitação não especificadas",
            "Dificuldade de Aprendizagem" => "( Transtorno de Aprendizagem )",
            "Discalculia - Criança" => "( Acalculia de Desenvolvimento )",
            "Distonia Orofacial Idiopática" => "(discinesia orofacial)",
            "Doença do Neurônio Motor" => "(Esclerose Lateral Amiotrófica)",
            "Surdez Neuro - Sensorial" => "( bilateral )",
            "Surdez Mista" => "( bilateral )",
            "Taquilalia" => "( linguagem precipitada)",
            "Transtorno Expressivo da Linguagem" => "(afasia de desenvolv. ou disfasia ex-pressiva de desenvolv.)",
            "Transtorno Receptivo da Linguagem" => "(agnosia auditiva congênita, surdez verbal, afasia de Wernicke)",
        ];

        if (DB::table('pathologies')->count() === count($pathologies))
            return true;
        foreach ($pathologies as $key => $value) {
            Pathology::create(["label" => $key,"description"=>$value]);
        }
    }
}
